name: TodoJourneyApp
options:
  minimumXcodeGenVersion: 2.32.0
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4

attributes:
  ORGANIZATIONNAME: "Giovanni Vicentin Moratto"

settings:
  base:
    SWIFT_VERSION: 5.7
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1"
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    DEAD_CODE_STRIPPING: YES
    COPY_PHASE_STRIP: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      ENABLE_TESTABILITY: YES
      ONLY_ACTIVE_ARCH: YES
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

targets:
  TodoJourneyApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App
      - path: Domain
      - path: Data
      - path: Presentation
      - path: Support
    resources:
      - path: Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.giovannimoratto.todojourney
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: App/Info.plist
    dependencies:
      - sdk: UIKit.framework
      - sdk: Foundation.framework

  TodoJourneyAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/Unit
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.giovannimoratto.todojourney.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TodoJourneyApp

  TodoJourneyAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/UITests
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.giovannimoratto.todojourney.uitests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TodoJourneyApp

schemes:
  TodoJourneyApp:
    build:
      targets:
        TodoJourneyApp: [all]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TodoJourneyAppTests
        - TodoJourneyAppUITests
      gatherCoverageData: true
      coverageTargets:
        - TodoJourneyApp
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

fileGroups:
  - App
  - Domain
  - Data
  - Presentation
  - Support
  - Resources
  - Tests
