name: TodoJourneyApp
options:
  postGenCommand: pod install --repo-update
  deploymentTarget:
    iOS: "15.0"
  indentWidth: 4
  tabWidth: 4

attributes:
  ORGANIZATIONNAME: "Giovanni Vicentin Moratto"

settings:
  base:
    SWIFT_VERSION: 5.7
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1"
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    COPY_PHASE_STRIP: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    ASSETCATALOG_COMPILER_OPTIMIZATION: space
    COMPRESS_PNG_FILES: YES
    STRIP_INSTALLED_PRODUCT: YES
    STRIP_STYLE: "all"
    PRODUCT_NAME: $(TARGET_NAME)
    PRODUCT_BUNDLE_IDENTIFIER: com.giovannimoratto.$(PRODUCT_NAME)
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      ENABLE_TESTABILITY: YES
      ONLY_ACTIVE_ARCH: YES
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      DEBUG_INFORMATION_FORMAT: dwarf
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -Osize
      ENABLE_TESTABILITY: NO
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      LLVM_LTO: YES_THIN
      DEAD_CODE_STRIPPING: YES
      STRIP_INSTALLED_PRODUCT: YES
      STRIP_STYLE: "all"
      OTHER_LDFLAGS: ["-dead_strip", "-dead_strip_dylibs"]

targets:
  TodoJourneyApp:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Presentation
      - path: Domain
      - path: Data
      - path: Support
    resources:
      - path: Resources
        optional: true
      - path: App/GoogleService-Info.plist
        optional: false
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: App/Info.plist

  TodoJourneyAppTests:
    type: bundle.unit-test
    platform: iOS
    gatherCoverageData: true
    dependencies:
      - target: TodoJourneyApp
    sources:
      - path: Tests/Unit
        optional: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  TodoJourneyAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/UITests
        optional: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TodoJourneyApp

schemes:
  TodoJourneyApp:
    build:
      targets:
        TodoJourneyApp: [all]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TodoJourneyAppTests
        - TodoJourneyAppUITests
      gatherCoverageData: true
      coverageTargets:
        - TodoJourneyApp
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

fileGroups:
  - App
  - Domain
  - Data
  - Presentation
  - Support
  - Resources
  - Tests
  - project.yml
